### ISSUE TITLE
Support for class properties

### ISSUE THREAD

**Issue by okcoker** [bvaughn/debounce-decorator#3]
``` js
// Works
class Some {
    @debouce
    method() {}
}

// Doesnt work
class Some {
    @debouce
    method = () => {}
}
```

**Comment by bvaughn** [comment]
Hey @okcoker,

I don't have any free cycles for the next couple of weeks. I'd love a hand with this if you'd like to submit a PR. 😄

**Comment by bvaughn** [comment]
I'm going to close this for now. Decorators are still in Stage 2 and I don't feel like putting a lot of effort into expanding the scope of support for this little lib until they proceed to stage 3.
