### ISSUE TITLE
Why declare react and react-dom as dependencies?

### ISSUE THREAD

**Issue by lijunle** [bvaughn/debounce-decorator#4]
Hi,

I saw react and react-dom and some unexpected dependencies are declared. I don't see the usages on them.

Could you please remove them from dependencies? That is expanding my dependencies tree.

Thanks!

**Comment by bvaughn** [comment]
Yeah, that's silly. They should be `devDependencies`.

**Comment by bvaughn** [comment]
Thanks for bringing this to my attention. This package was all kinds of clowny before WRT deps.

Check out [version 1.0.6](https://unpkg.com/debounce-decorator@1.0.6/). Should work better for you.
