### ISSUE TITLE
Late debounce value definition

### ISSUE THREAD

**Issue by Webbrother** [bvaughn/debounce-decorator#5]
Hi!
This is improvement suggestion.
It would be great if it would be possible to use class instance property value to define debounce duration.
I mean:
```
import Debounce from 'debounce-decorator'

class MyComponent {
  constructor() {
    this._debounce = 250; // <- here we define debounce value
    document.addEventListener('keyup', this.onKeyUp)
  }

  @Debounce() // <- no debounce value here
  onKeyUp(event) {
    // This code will be debounced by 250ms
  }
}
```
Such implementation has good advantage: we could define debounce value during instantiation (but not during class definition)

**Comment by bvaughn** [comment]
Feel free to submit a PR. I'll consider it. 😄
