### ISSUE TITLE
How to Debounce Class Methods with function debounce

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [bvaughn/debounce-decorator#7]
Hey, I'd like to create a map of debounced functions that link to a class method. Is this possible?

**Comment by bvaughn** [comment]
That doesn't sound like something this decorator would be useful for.

**Comment by TimeTravelersHackedMe** [comment]
Because it will not be able to support it or? I'm trying to make the
function retain its context. I.e. I need to access "this" inside of the
function I'm debouncing

**Comment by bvaughn** [comment]
Maybe I just misunderstood what you were asking. Your question is kind of vague.

If you're just looking for a way to attach functions to the instance with the correct `this` then you can just do:
```js
import { debounce } from "debounce-decorator";

class Example {
  constructor() {
    this.onClick = debounce(() => {
      console.log("onClick() this:", this);
    });
    window.addEventListener("click", this.onClick);
  }
}
```

[CodeSandbox](https://codesandbox.io/s/zwj7zww8k4)
